### PR TITLE
Update: Get in touch,Our responsibility, Src allignment

### PR DESCRIPTION
**Pull request by Abraralvi2002**

### CODE REVIEW

**Comment by Abraralvi2002** [comment]
Thank you so much.

**Comment by rahulroynipon** [comment]
vlo na re vai jibon tai bitha

**Comment by Abraralvi2002** [comment]
Taile Vitamin-C khao.

**Comment by Abraralvi2002** [comment]
President ke bol kichu taka poysha dite jate tui Vitamin-C kheye shorir mon dutai valo rakhte parish.

**Comment by Abraralvi2002** [comment]
Okay ami suparish korboni tor jonno. :)

**Comment by rahulroynipon** [comment]
thank you vai buk a ai tui chara kosto ta keu bujlo na

**Pull request merged**
